- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-0696dc92e81135eee # replace with your SG ID
    zone_id: "Z09288351F1RG63CMSZ8A" # replace with your ID
    domain_name: "msdevsecops.fun"
    # we can pass instances through command line using -e
    instances: 
    - mongodb
    # - redis
    # - mysql
    # - rabbitmq
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group:  "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: "{{ ec2-output }}"

  - name: print the ec2 output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"
