- name: setup cart server
  hosts: cart.msdevsecops.fun
  become: yes
  tasks:
  - name: disable nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
     name: nodejs
     state: present
  
  - name: create roboshop system user 
    ansible.builtin.user:
      name: roboshop
      comment: roboshop system cart
      shell: /sbin/nologin
      home: /app
      system: true

  - name: Remove file (delete file)
    ansible.builtin.file:
      path: /app
      state: absent

  - name: Create app directory 
    ansible.builtin.file:
     state: directory
     path: /app
     

  - name: delete cart file (delete file)
    ansible.builtin.file:
      path: /tmp/cart.zip
      state: absent

  - name: to download the cart application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip 
      dest: /tmp/cart.zip

  - name: Extract 
    ansible.builtin.unarchive:
     src: /tmp/cart.zip
     dest: /app
     remote_src: yes

  - name: Install dependencies
    community.general.npm:
     path: /app

  - name: copy cart service
    ansible.builtin.copy:
     src: cart.service
     dest: /etc/systemd/system/cart.service

  - name: reload and start cart
    ansible.builtin.systemd_service:
      name: cart
      state: started
      daemon_reload: true
      enabled: true
