- name: setup catalouge server
  hosts: catalogue
  become: yes
  tasks:
  - name: disable nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      comment: roboshop system user
      system: true
      shell: /sbin/nologin
      home: /app

  - name: Remove file (delete file)
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create directory
    ansible.builtin.file:
      state: directory
      path: /app

  - name: delete catalouge file (delete file)
    ansible.builtin.file:
      path: /tmp/catalogue.zip
      state: absent


  - name: download catelouge application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: /tmp/catalogue.zip

  - name: Extract catalouge application
    ansible.builtin.unarchive:
     src: /tmp/catalogue.zip
     dest: /app 
     remote_src: yes

  - name: Install dependencies
    community.general.npm:
      path: /app

  - name: copy catalogue services
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service  

  - name: copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo 

  - name: install mongodb client
    ansible.builtin.package:
      name: mongodb-mongosh
      state: present

  - name: connect to mongodb catalouge
    ansible.builtin.command: mongosh mongodb.msdevsecops.fun --quiet --eval "db.getMongo().getDBNames().indexOf('catalouge')"
    register: catalouge_output

  - name: print catalouge_output
    ansible.builtin.debug:
      msg: "{{ catalouge_output }}"

  - name: load product into mongodb
    ansible.builtin.shell: mongosh --host mongodb.msdevsecops.fun </app/db/master-data.js
    when: catalouge_output.stdout | int < 0
       
  - name: start and enable the catalouge
    ansible.builtin.systemd_service:
      name: catalogue
      state: started
      enabled: true
      daemon_reload: true