- name: setup user server
  hosts: user.msdevsecops.fun
  become: yes
  tasks:
  - name: disable nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
     name: nodejs
     state: present
  
  - name: add application user
    ansible.builtin.user:
      name: roboshop
      comment: roboshop system user
      shell: /sbin/nologin
      home: /app
      system: true

  - name: Remove file (delete file)
    ansible.builtin.file:
      path: /app
      state: absent

  - name: Create app directory 
    ansible.builtin.file:
     path: /app
     state: directory

  - name: delete catalouge file (delete file)
    ansible.builtin.file:
      path: /tmp/user.zip
      state: absent

  - name: to download the user application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip 
      dest: /tmp/user.zip

  - name: Extract 
    ansible.builtin.unarchive:
     src: /tmp/user.zip
     dest: /app
     remote_src: yes

  - name: Install dependencies
    community.general.npm:
     #name: npm
     path: /app

  - name: copy user service
    ansible.builtin.copy:
     src: user.service
     dest: /etc/systemd/system/user.service

  - name: reload and start user
    ansible.builtin.systemd_service:
      state: started
      daemon_reload: true
      enabled: true
